### ISSUE TITLE
Reading a specific IMU

### ISSUE THREAD

**Issue by gepopa10** [BluDay/wiiproxy#10]
Hi,

how can I read a specific IMU for example, the angular speed in x axis?

When I use controller.get_imu(False), I get the IMU values but each time I run the script the values are ordered differently so I can't read the angular speed because it's not at the same position.

Also, controller.get_imu(True) gives different values from when it's False.

Can you please clarify this.

Thanks

**Comment by bluday** [comment]
Hello, I apologize for being late.

The `get_imu()` method with `raw = True` returns unaltered values, directly.

According to the MSP documentation, the format of the `MSP_RAW_IMU` operation is `accx accy accz gyrx gyry gyrz magx magy magz` and consists only of the type `INT 16`. 

On the first row of the `MSP_RAW_IMU` operation, the following statement is made:

> unit: it depends on ACC sensor and is based on ACC_1G definition
> 
> MMA7455 64 / MMA8451Q 512 / ADXL345 265 / BMA180 255 / BMA020 63 / NUNCHUCK 200 / LIS3LV02 256 / LSM303DLx_ACC 256 / MPU6050 512 / LSM330 256 

I only have two MPU6050 sensors at the moment. You should at least attempt to configure the ACC part of the MultiWii firmware. 

If you've already configured it to no avail, please provide more details of your hardware and software.

**Comment by gepopa10** [comment]
Hi,
thanks for the elaborated  response  I figured out that I just had to do get_imu(False)['gyrx'] to get a specific value, it's was more of a python incomprehension I guess.

**Comment by bluday** [comment]
That's a relief...

The purpose of the `raw` arguments were simply just to provide the user efficiency and flexiblilty. Some likes to modify the data themselves, other prefer explicitly formatted data.

If you're successfully flying your craft with this module, please let me know.

Good luck...
