### ISSUE TITLE
MSP v2 support?

### ISSUE THREAD

**Issue by wx4cb** [BluDay/wiiproxy#11]
Does this library support MSP v2 as used in the current (2.1.x versions of inav?

I'm hunting for a library that can do msp V2 and all i have found right now are V1 protocol libraries?

**Comment by bluday** [comment]
Greetings @wx4cb

This library does not support MSP version 2 at the moment. 

Do you have know where I can find the documentation for MSP version 2?  

I'm interested in creating support it...

**Comment by wx4cb** [comment]
the base protocol is the same i beleive, here are the inav specific changes

https://github.com/iNavFlight/inav/wiki/MSP-V2
https://github.com/iNavFlight/inav/wiki/MSP-Navigation-Messages
https://github.com/iNavFlight/inav/wiki/INAV-MSP-frames-changelog

**Comment by wx4cb** [comment]
here: https://github.com/iNavFlight/inav/wiki/MSP-V2
