### ISSUE TITLE
Is calibration achievable

### ISSUE THREAD

**Issue by weixingsun** [BluDay/wiiproxy#12]
I am able to takeoff my quad by using your lib now, but gyro is tilting all the time, So I came to get help again. 
Could you help to create a method to calibrate the gyro/accel/meg from MSP protocol?

Thanks

**Comment by bluday** [comment]
Hello...

Did you try to use the `calibrate_mag()` method?

The **MSP_MAG_CALIBRATION** command takes no parameters and should just work...

**Comment by weixingsun** [comment]
Thanks for replying, I didn't try calibrate_acc, but something like calibrate_gyro is what I am looking for, does it integrated to acc method together?

**Comment by bluday** [comment]
I was referring to the `calibrate_mag()` method, not the `calibrate_acc()` method.

I found a [GYROCALIBRATIONFAILSAFE](https://github.com/multiwii/multiwii-firmware/blob/e957a701844a9ecf0d19ac6a7e3ea1e8d81cc43b/config.h#L580) macro in the configuration header of the firmware.

You could also try to follow the instructions of the [Calibration Gyroscope](www.multiwii.com/wiki/index.php?title=Calibration_Gyroscope) documentation page. You could implement a custom function in your program that emulates a manual calibration via the `set_channels()` method...

**Comment by weixingsun** [comment]
thanks, I will give it a try
