### ISSUE TITLE
How to arm using AUX

### ISSUE THREAD

**Issue by weixingsun** [BluDay/wiiproxy#13]
I saw your code of arm is using stick motions, but in most FC now disabled this method(like betaflight), since these stick combinations may be unintentionally triggered in acro mode.
I did some changes in your arm() code, by adding aux 1 ~4, but looks like the aux channels doesn't make it arm in any way..
Could you help to give an idea of what is the reason?

**Comment by bluday** [comment]
Please show me your AUX payload.

**Comment by weixingsun** [comment]
When I set aux1 for arming in range of [1400-1600] in cleanflight/betaflight/inav configurator 
Then send [1500,1500,1500,1200, 1500,1000,1000,1000] means throttle=1200(min_throttle=1150), arming enabled(in 1400-1600), but my motor doesn't spin
I want to know the reason, thanks a lot

**Comment by bluday** [comment]
Which channels are you using to arm your craft?
