### ISSUE TITLE
PID get & set

### ISSUE THREAD

**Issue by cmb87** [BluDay/wiiproxy#16]
Hi engineer-99b,
I'm using your package for communication between my MultiWii flightcontroller and an onboard Raspberry Pi and I'm very satisfied with your solution. So thanks for that!

One request I would like to bother you with is the implementation of a set / get PID method. That would be very neat, so you could tune the controller 100% online without the need of using the MultiWii Gui.

From https://github.com/alduxvm/pyMultiWii I know the code to set PID is 202 and to get is 112.

**Comment by bluday** [comment]
Hello @cmb87.

I will implement functionalities for PID and EEPROM soon. I'm currently upgrading the module...

**Comment by bluday** [comment]
Hello again @cmb87

I rewrote the module completely, have a look.

**Comment by cmb87** [comment]
Hi @engineer-99b, brilliant! I'll check it out shortly and thanks for that.

 Maybe some more ideas (this is aside of this topic). I guess you are familiar with microPython? I recently played around with it and burned it on an ESP8266 based Wemos D1. Natively, microPython comes with a built in serial protocol and by just taking a glimpse, I believe extending your library for microPython is quite straight forward (you merely need to replace the serial package by the microPython's one). With that you could enable wifi based bidirectional communications with websockets. I'll definitely will try to port your code for that, but maybe it also sounds interesting for you.

Thanks again!
