### ISSUE TITLE
support needet

### ISSUE THREAD

**Issue by urpils4711** [BluDay/wiiproxy#17]
Hi BluDay,
i'm missing the setup.py file for using your software.

can you pls shre it?

**Comment by BluDay** [comment]
> Hi BluDay, i'm missing the setup.py file for using your software.
> 
> can you pls shre it?

Hello!

Run `pip install .` or `poetry build` to install the package. I removed `setup.py` and `setuptools` a few months ago.

**Comment by bluday** [comment]
> Hi BluDay, i'm missing the setup.py file for using your software.
> 
> can you pls shre it?

Hello!

Run `pip install .` or `poetry build` to install the package.
