### ISSUE TITLE
Arming doesnt work

### ISSUE THREAD

**Issue by rapop** [BluDay/wiiproxy#5]
I tested your module on Crius MultiWii SE v2.6 and the reading of heading and angles works.

But the arming part doesnt arm my motors.

**Comment by bluday** [comment]
Please provide the arming segment of your code.

It is not possible to simultaneously arm and disarm while operating the craft.

Kindly ensure your serial port settings are correctly set. 
The primary documentation provides all required instructions for
properly establishing a serial port connection with the flight controller.
