### ISSUE TITLE
set_channels doesnt work

### ISSUE THREAD

**Issue by rapop** [BluDay/wiiproxy#6]
Im using MultiWii Crius SE v2.6

First, im getting my channels with get_channels and it work fine.  But after I try to set new channels with set_channels and then printing their values and they are really weird. 

See code : 
```
import json
import serial as pyserial

from os         import system
from time       import sleep
from WiiProxy   import MultiWii

serial = pyserial.Serial()

serial.port             = "/dev/ttyUSB0"
serial.baudrate         = 115200
serial.bytesize         = pyserial.EIGHTBITS
serial.parity           = pyserial.PARITY_NONE
serial.stopbits         = pyserial.STOPBITS_ONE
serial.write_timeout    = 3
serial.xonxoff          = False
serial.rtscts           = False
serial.dsrdtr           = False

serial.open()

sleep(6)

system("clear")

controller = MultiWii(serial)

print("\nChannels")
print(controller.get_channels(True, True))
#channels = [roll (ch1), pitch(ch2), yaw(ch4), throttle (ch3), aux1(ch5), aux2 (ch6)]
channels = [1500, 1500, 1500, 1000, 2000,1000]
while True:
    controller.set_channels(channels)
    print(controller.get_channels(True, True))
    #print(controller.get_altitude)
    
serial.close()
serial = None
```
The result : 

![image](https://user-images.githubusercontent.com/45318548/49838322-27c62500-fd78-11e8-8b1c-ef5074b43589.png)

(if you stop the while loop after 2 iterations of course)

Notice that whatever value you put in the channels it gives for the first three channels those values around 0. So it isnt a constant error.

I hope it can be easily solved

**Comment by rapop** [comment]
The problem was that I kept the modified line in Protocole.cpp file in the MultiWii from the other guy that did this module for python 2

**Comment by bluday** [comment]
It's good to know why this issue occured. Good job.

If you're successfully flying your craft with this module, please let me know.

Good luck...

**Comment by rapop** [comment]
Yes it works great.
Good job !
