### ISSUE TITLE
set_motors/get_motors issue

### ISSUE THREAD

**Issue by weixingsun** [BluDay/wiiproxy#7]
Thanks for making this module, I like this py3 codes
I am trying to get/set motors as below code snippet:
####################################################################
try:
    
    print("\nMotors")
    print(controller.get_motors())
    
    print("\nSet Arm")
    print(controller.arm())
    
    print("\nSet Motors")
    print(controller.set_motors([1050,1050,1050,1050]))
    
    print("\nMotors")
    print(controller.get_motors())
    
    print("\nSet Disarm")
    print(controller.disarm())
except KeyboardInterrupt:
    exit()
####################################################################
sun@sun:~/WiiProxy$ ./test.py
Motors
[1000, 1000, 1000, 1000, 0, 0, 0, 0]

Set Arm
None

Set Motors
None

Motors
[9430, 15949, 26640, 1049, 1049, 1049, 1049, 0]

Set Disarm
None
sun@sun:~/WiiProxy$ ./test.py
Motors
[1049, 1049, 1049, 1049, 0, 0, 0, 0]

Set Arm
None

Set Motors
None

Motors
[9430, 15949, 26640, 1049, 1049, 1049, 1049, 0]

Set Disarm
None
sun@sun:~/WiiProxy$

**Comment by bluday** [comment]
Please note that you're not supposed to print outgoing commands.

The result of `get_motors()` is indeed incorrect and unexpected.

What is your craft "multitype" and configuration?

The `get_motors()` method follows the code MSP_MOTOR which should return 
all 8 motor values, even if your craft consists of less than 8 motors.

Please, try to insert 8 values instead of 4 and share the output of that...

**Comment by weixingsun** [comment]
Thanks for your reply, the values looks wrote correctly, but read function got confused, 
I had done with 8 values, I remember it shown exactly same output, I will upload it later
my quadrotor mounts an omnibus f4 flight controller, running betaflight 3.5.0

**Comment by weixingsun** [comment]
I saw exactly same result when using 8 values, 
But all my motors were running correctly, so the mess is only in get_motors, and only after set_motors
any ideas ?

**Comment by bluday** [comment]
Excuse me for my delayed reply...

There's a high possibility that the `get_motors()` method is incorrectly decoding the output values.

Then again, the MSP documentation does indeed list the data types for MSP_MOTOR as `UINT16` or more specifically `16 * UINT 16`.

I'll attempt to resolve this issue. I'll be back in a moment...

**Comment by weixingsun** [comment]
I got some more work done:
(1) add prints in your code:
    def _write_read(self, code: int, size: int, pattern: str):
        command = self._construct_payload(code)
        print("command= "+str(command))                          
        self._write(command)
        payload = self._read(size)
        print("payload= "+str(payload))                               
        return self._destruct_payload(payload, pattern)
....
and rerun my test:

$ python3 test.py 

get_motors() 
command= b'$M<\x00hh'
payload= b'\x19\x04\x19\x04\x19\x04\x19\x04\x00\x00\x00\x00\x00\x00\x00\x00'
[1049, 1049, 1049, 1049, 0, 0, 0, 0]

arm() 
None

set_motors() 
None

get_motors() 
command= b'$M<\x00hh'
payload= b'\xd6$M>\x10h\x19\x04\x19\x04\x19\x04\x19\x04\x00\x00'
[9430, 15949, 26640, 1049, 1049, 1049, 1049, 0]

disarm() 
None

**Comment by weixingsun** [comment]
@engineer-186f 
I am thinking the root cause is we need some time for FC to proceed, 
After I added following line to all the set_* methods, the problem went away.
sleep(MultiWii.WRITE_DELAY)

I don't know how small this delay could be, but it may depends on the MCU of the board.

**Comment by bluday** [comment]
Yes...

It seems as if the payload was shattered or incomplete. I strongly advise you not to print anything in the module itself. The module should be completely "headless".

I added `sleep(WRITE_DELAY)` to the `_write()` method, thus eliminating the need of adding `sleep(WRITE_DELAY)` to every `set_*()` method.

Be careful when using `sleep(WRITE_DELAY)` for the RC channels. If the WRITE_DELAY constant is to high, the RC channel inputs will be reset automatically.

**Comment by weixingsun** [comment]
Thanks for your quick fix, 
Btw, it should be self.WRITE_DELAY instead of WRITE_DELAY
And, what is the WRITE_DELAY you recommend for RC channels ? 
this can be very tricky number, too short will not be enough for MCU to process, too long is bad for RC input reset.

**Comment by bluday** [comment]
Yes, I've corrected it.

The processing speed depends on the clock speed or frequency of your FC's microprocessor. I own a MultiWii Crius SE V2.6 and it has an ATmega328P chip clocked at 20Mhz. 

Delaying each write operation with 50ms works splendid for me. My FC is flashed with legacy MultiWii firmware. Try delaying each operation with 50-150ms...

**Comment by weixingsun** [comment]
Wait a bit, have you tested the latest code on your board ? 
My code hanging there when the sleep moved to after write(command), I don't know why
sleep before write (your previous code) works for my F4 Betaflight board
