### ISSUE TITLE
set_channels/get_channels ordering

### ISSUE THREAD

**Issue by weixingsun** [BluDay/wiiproxy#8]
("roll", "pitch", "throttle", "yaw") is for get or set ?
Here is my output:

channels=[1501, 1502, 1503, 1004]
set_channels( channels ) 

get_channels() 
[1501, 1502, 1004, 1503]

**Comment by bluday** [comment]
I'm aware of the ability to map your RC channels with CF and BF.

The MSP documentation states that the default order of the RC channels is:

`ROLL | PITCH | YAW | THROTTLE` following with `AUX 1 | AUX 2 | AUX 3 | AUX 4`

This RC order functions correctly on legacy flashed FCs.

Try remapping your RC channels using BF before modifying the module...

**Comment by weixingsun** [comment]
Yes, I got the correct results after changing my receiver protocol.
Thanks a lot
