### ISSUE TITLE
motors not spin when set_channels() after arm()

### ISSUE THREAD

**Issue by weixingsun** [BluDay/wiiproxy#9]
I tested most functions on my F4 board with Betaflight 3.5.1
Cannot arm my board from your API MultiWii.arm()
Here is my steps:

arm()
channels = [1500, 1500, 1500, 1050]  #roll pitch yaw throttle
set_channels(channels)
print(get_channels())
print(get_motors())
disarm()

And my outputs:
{'roll': 1500, 'pitch': 1500, 'throttle': 1050, 'yaw': 1500}
[1000, 1000, 1000, 1000, 0, 0, 0, 0]
_______________________________
Channels work, but MSP RC signals didn't make any change on motors, they are working independently, 

Btw, set_motors() method can work without arm(),

**Comment by bluday** [comment]
I had the same issue myself a while ago. I realized the fact that the board needs to idle or sleep for at least two seconds before perfoming the arm/disarm operation.

Try to delay the operation by a few seconds when using the arm() and disarm() methods.

I suspect that you do not require your craft to be armed/disarmed instantaneously?

My initial plan consisted of me having a foldable craft capable of arming in a matter of seconds when throwing it, after the OS and my program initiates...

**Comment by weixingsun** [comment]
Thanks for your reply on holiday, I appreciate it so much. 
I will give it a try shortly, and wish you a merry Christmas !

**Comment by bluday** [comment]
I'm available anytime.

I don't celebrate holidays... but... merry christmas to you as well.

**Comment by weixingsun** [comment]
Thanks for your advice, "sleep 3" works for me,

**Comment by bluday** [comment]
No problem, I'm always available...

If you're successfully flying your craft with this module, please let me know.

Good luck...

**Comment by weixingsun** [comment]
the controller function is working, but I have to develop a self-balancing algorithm, to ensure less crashing incidents :-) 
Thanks again to make it working on p3, there is nobody maintaining py2 modules
